### ISSUE TITLE
Error Building Android apk in Unity - Failed to execute aapt

### ISSUE THREAD

**Issue by AirGeoff** [foursquare/pilgrim-unity-sdk#10]
Hello, I am having an issue on the Android side this time with building an apk file. I am using v1.0.1. When I try to build an apk file I am receiving a build failure error stating "Failed to execute aapt See the Console for details.

It seems there is an issue with a fontstyle, font, and fontweight not being found? I am placing the console output in a txt file. Please see attached txt file for the console output:

[Pilgrim Android Build Failure - Console Output - 02-20-2019.txt](https://github.com/foursquare/pilgrim-unity-sdk/files/2886966/Pilgrim.Android.Build.Failure.-.Console.Output.-.02-20-2019.txt)

Please help me get this building. Thank you in advance for your time and help!
.

**Comment by marchinram** [comment]
The console output says it's using `support-compat-26.1.0` however we use `support-compat-27.0.1` for Pilgrim, this may be a gradle caching issue, you could try removing `com.android.support.support-compat-26.1.0.aar` from the `C:\Users\geoff\.gradle\caches\transforms-1\files-1.1` or just delete the entire `C:\Users\geoff\.gradle\caches` directory and rebuild.

**Comment by AirGeoff** [comment]
I deleted the whole cache folder and tried to rebuild and am still receiving the same error. Still showing the support-compat-26.1.0 in the console too.

**Comment by marchinram** [comment]
Which version of Android Studio are you using?  I'll try to repro this

**Comment by AirGeoff** [comment]
I think the latest, Android studio version 3.3.1.

**Comment by AirGeoff** [comment]
@marchinram Any update on this issue? As far as I can tell I think I need to edit the AndroidManifest.xml file or setup a custom mainTemplate.gradle file (build.gradle template in Unity) which I tried by adding this line under the dependencies section:

 compile "com.android.support:appcompat-v7:24.2.1"

This did not help resolve the issue unfortunately, and this issue is very difficult to research on Google.
Any luck from your end or any idea how to resolve it?

**Comment by AirGeoff** [comment]
Slight update, I made a custom build.gradle with 'buildToolsVersion "27.0.1"'. I am now getting a new build error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformResourcesWithMergeJavaResForRelease'.
> More than one file was found with OS independent path 'play-services-ads-identifier.properties'

Up at the top of the console it also says:

Could not load custom lint check jar file C:\Users\geoff\.gradle\caches\transforms-1\files-1.1\pilgrimsdk-2.1.2.aar\dbfceb296fa05e324a17bbe709b32798\jars\lint.jar

What am I missing here? I really need to get this building again.

**Comment by marchinram** [comment]
Hey @AirGeoff sorry for the delay i'm looking into this now

**Comment by joshafeinberg** [comment]
@AirGeoff I believe you should be able to fix this by doing

```
android {
      packagingOptions {
        exclude 'play-services-ads-identifier.properties'
      }
    }
```

In your build.gradle file. Can you please test that and see if that works

**Comment by AirGeoff** [comment]
Update: So I thought I had fixed the original AAPT error by setting the build tools version in the build.gradle file like I said in my previous comment, because I was able to get past that error somehow, but this morning I tried to build again (and have not yet made any changes), and I am now back to the same AAPT error again. 

I'm not sure what happened cause I thought I got past this and was even trying out the AndroidDuplicatePluginDisabler last night to fix this new error (which on another note the link for this under the PilgrimMapbox sample is dead and I had to go back a few commits to find the script to try it out).

The duplicate plugin disabler seemed to help, as I finally created an apk file, but it just crashes immediately upon launching the app. I had reverted my changes from adding it in and expected to be back at the play-services-ads-identifier error, but am now back at the AAPT error and my build.gradle is still the same.

Attached is the console output from this morning, my mainTemplate.gradle (changed to .txt to allow to upload here), and my AndroidManifest.xml (also changed to .txt to allow upload).
Also we are still using Unity 2018.2.6f1 and Android Studio 3.3.1.

[AAPT Build Error.txt](https://github.com/foursquare/pilgrim-unity-sdk/files/2907567/AAPT.Build.Error.txt)

[mainTemplate.gradle.txt](https://github.com/foursquare/pilgrim-unity-sdk/files/2907586/mainTemplate.gradle.txt)

[AndroidManifest.xml.txt](https://github.com/foursquare/pilgrim-unity-sdk/files/2907587/AndroidManifest.xml.txt)

**Comment by marchinram** [comment]
Ok I'll check this out, that duplicate plugin disabler is just a sample for that map box demo, shows how to programmatically disable plugins, not intended for general use so not sure if it'll work for you, i'll check out the build errors you sent

**Comment by marchinram** [comment]
I was able to repro the issue you're seeing by setting the `compileSdkVersion 25` in the `build.gradle` file.  To fix I set `compileSdkVersion 27` and it built fine for me.  Can you please try this and let me know

**Comment by AirGeoff** [comment]
Hi @marchinram this does resolve the AAPT build issue, but now I am again getting the "More than one file was found with OS independent path 'play-services-ads-identifier.properties'" error again. I now realize that I had tried setting the different Android SDK versions in the build.gradle file the other day and that is probably how I got to the play-services-ads error at that time.

I just tried adding the packagingOptions to exclude this file like suggested above, however I am still receiving the same play-services-ads error even after doing so.

Also on another note, changing to Android v27 is not really an ideal solution for us. We are hoping to target as many devices as possible that support AR functionality, which meant a minimum Android v24. I also just tried building on Android v26 as this is now the new standard that Google requires for publishing to the play store anyways, so we likely need to increase our minimum required SDK to this level anyways, and want to confirm that v26 also solves the AAPT error for me, but is still giving the play-services-ads error on build. Now that we are here though I think this original issue is technically solved and the play-services-ads error is a different issue which is related to duplicate android plugins?

**Comment by marchinram** [comment]
Ok cool glad we're past that first issue.  Yeah the reason we needed 27 (and looks like it works for 26 too) is to support the [Debug Screen](https://github.com/foursquare/pilgrim-unity-sdk#debug-screen) feature which requires appcompat-v7:27.0.1. 

For the duplicate dependencies issue it's hard to diagnose because I don't know what your dependencies are your build.gradle omits them, but if you're able to send them over I can let you know which ones would conflict with Pilgrim dependencies.  Then in Unity you just need to select the duplicate .jar/.aar file in the project view, and in the inspector view uncheck them for Android in the `Select platforms for plugin` section so they don't get copied to the generated project.  That's essentially what [AndroidDuplicatePluginDisabler](https://github.com/foursquare/pilgrim-unity-sdk/blob/master/samples/PilgrimMapbox/Assets/PilgrimMapbox/Scripts/Editor/AndroidDuplicatePluginDisabler.cs) does, however it may not work as is for your project depending on how your project is structured.

**Comment by AirGeoff** [comment]
The build.gradle I sent earlier was just the template from before compiling. Here is the one that is created during build that I think helps show all the dependencies:

[build.gradle.txt](https://github.com/foursquare/pilgrim-unity-sdk/files/2908498/build.gradle.txt)

**Comment by marchinram** [comment]
Hey @AirGeoff, so I see a many duplicates .aars in the build.gradle, not sure about the .jar file they are in the libs dir, there may be dups there too.
```
implementation(name: 'com.google.android.gms.play-services-ads-identifier-15.0.1', ext:'aar')
implementation(name: 'play-services-ads-identifier-16.0.0', ext:'aar')

implementation(name: 'com.google.android.gms.play-services-base-15.0.1', ext:'aar')
implementation(name: 'play-services-base-16.0.1', ext:'aar')

implementation(name: 'com.google.android.gms.play-services-basement-15.0.1', ext:'aar')
implementation(name: 'play-services-basement-16.0.1', ext:'aar')

implementation(name: 'com.google.firebase.firebase-iid-16.0.0', ext:'aar')
implementation(name: 'play-services-iid-16.0.0', ext:'aar')

implementation(name: 'com.google.android.gms.play-services-stats-15.0.1', ext:'aar')
implementation(name: 'play-services-stats-16.0.1', ext:'aar')

implementation(name: 'com.google.android.gms.play-services-tasks-15.0.1', ext:'aar')
implementation(name: 'play-services-tasks-16.0.1', ext:'aar')

implementation(name: 'recyclerview-v7', ext:'aar')
implementation(name: 'recyclerview-v7-27.0.1', ext:'aar')

implementation(name: 'android.arch.lifecycle.runtime-1.0.0', ext:'aar')
implementation(name: 'runtime-1.0.0', ext:'aar')

implementation(name: 'com.android.support.support-compat-26.1.0', ext:'aar')
implementation(name: 'support-compat-27.0.1', ext:'aar')
implementation(name: 'support-compat', ext:'aar')

implementation(name: 'com.android.support.support-core-ui-26.1.0', ext:'aar')
implementation(name: 'support-core-ui-27.0.1', ext:'aar')
implementation(name: 'support-core-ui', ext:'aar')

implementation(name: 'com.android.support.support-core-utils-26.1.0', ext:'aar')
implementation(name: 'support-core-utils-27.0.1', ext:'aar')
implementation(name: 'support-core-utils', ext:'aar')

implementation(name: 'com.android.support.support-fragment-26.1.0', ext:'aar')
implementation(name: 'support-fragment-27.0.1', ext:'aar')

implementation(name: 'com.android.support.support-media-compat-26.1.0', ext:'aar')
implementation(name: 'support-media-compat-27.0.1', ext:'aar')

implementation(name: 'com.android.support.support-v4-26.1.0', ext:'aar')
implementation(name: 'support-v4-27.0.1', ext:'aar')
implementation(name: 'support-v4', ext:'aar')
```

Additionally, Pilgrim uses the following jars:
```
common-1.0.0.jar
common-1.1.1.jar
core-0.29.jar
cupboard-2.2.0.jar
gson-2.8.2.jar
okhttp-3.9.0.jar
okio-1.13.0.jar
simple-0.29.jar
support-annotations-27.0.1.jar
```

Pilgrim requires 27.0.1 for all the support libs and 16.0.1 for all the play service libs

**Comment by marchinram** [comment]
Also setting the `compileSdkVersion 27` in your build.gradle will not cause you to lose any users if you set the `minSdkVersion` to whatever level you want to support down to.  And since pilgrim uses `27.0.1` for all the support libs you really should set the `compileSdkVersion 27`

**Comment by AirGeoff** [comment]
@marchinram I noticed some of these after I sent it to you and have disabled some of them already, but still receiving the play-services-ads-identifier error. Some of the other ones too I am not seeing the library in the project files and am having a hard time tracking down where they are coming from.

Would there be a way to write an AndroidDuplicatePluginRemover script that would prioritize all the Pilgrim dependencies and disable the conflicting dependencies?

Also thank you for the info on the compile version! I set the compileSDKVersion to 27 in the build.gradle as you suggested and am keeping the minimum at 24.

**Comment by marchinram** [comment]
@AirGeoff I'm not sure about the play services error, I'll have to try to repro it and get back to you.  Also you could potentially write a duplicate disabler script however it would depend on how the files are named.  In my script I get all the Android plugins and use a regex to look for ones with the same name and then check the version, so depending on how the .aar/.jar are named or renamed it may not work. 

Also it can be tricky to find files in a large Unity project, can get unwieldy, but you can search in the project view where the magnifying glass is, just start typing the name of the plugin in the list i sent and it should filter and show them.

**Comment by marchinram** [comment]
Resolved, the issue was related to AppCenter integration
