### ISSUE TITLE
Error with iOS Signing on XCode -  Failed to Verify Bitcode in Pilgrim.framework/Pilgrim

### ISSUE THREAD

**Issue by AirGeoff** [foursquare/pilgrim-unity-sdk#8]
Hi Foursquare team!

We are receiving an error when attempting to distribute our app in xcode. The build is succeeding, however when you select to distribute the app we are receiving an error that states:

Failed to verify bitcode in Pilgrim.framework/Pilgrim:
error: Cannot extract bundle from /var/folders/r8/2_5xnmrd2_z1v0vz2194qbr0000gp/T/
IDEDistributionOptionThinning.~~~7FbtzZ/Payload/AirEverywherePOC.app/Frameworks/Pilgrim.framework/Pilgrim (i386)
![image](https://user-images.githubusercontent.com/47788677/53030707-39831300-3420-11e9-91cf-f97decd21e24.png)

Also if we turn off app thinning we can get one step further than this error, but then receive this error:

Code signing "Pilgrim.framework" failed.
![image from ios](https://user-images.githubusercontent.com/47788677/53030734-46a00200-3420-11e9-9070-76c477709c16.jpg)

which doesn't say anything more than that and says to view the distribution logs for more information.

We can disable bitcode to get this to go through successfully, however this would also mean that it won't be optimally recompiled at the bit code level.

Can you please help us to figure out this issue?

**Comment by marchinram** [comment]
Hello, I'm looking into this now, in the mean time can you tell me which release you are using?

**Comment by AirGeoff** [comment]
Hello! This is happening in both v1.0.1 and v1.0.2.

**Comment by marchinram** [comment]
The problem is that Pilgrim is a fat binary with `i386`, `x86_64`, `armv7`, `arm64` architectures.  Xcode is trying to rebuild with bitcode for `i386` and `x86_64` architectures (which are included in the Pilgrim framework to support running on the simulator).  These architectures however don't support bitcode, to fix remove the architectures from the binary in the framework in Xcode. (more info here: https://stackoverflow.com/a/46710698/302925)
```
cd Pilgrim.framework
lipo -remove i386 -o Pilgrim
lipo -remove x86_64 -o Pilgrim
```
Obviously this isn't an ideal solution since every time you build from Unity for iOS it will overwrite the `Pilgrim.framework` file and the binary will be the fat version with `i386` and `x86_64`.  I will look into adding a run script build phase when building Unity project for iOS which automatically removes these architectures when archiving.

You can also remove the architectures from the `Pilgrim.framework` file in `Assets/PilgrimUnitySDK/Plugins/iOS` however then you couldn't run on simulator so I wouldn't recommend this.

**Comment by marchinram** [comment]
@AirGeoff Pigrim actually comes with a script to strip out those architectures, in `Pilgrim.framework/strip-frameworks.sh`. You can add a Run Script build phase like below for now:

![screen shot 2019-02-20 at 12 59 20 pm](https://user-images.githubusercontent.com/197929/53117092-b6d98100-350f-11e9-9979-7a9a5bb988bf.png)

I will try to get a release out asap that will automatically add this to the Xcode project when build for iOS from Unity

**Comment by nkanetka** [comment]
`bash "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Pilgrim.framework/strip-frameworks.sh"` is the run script you need :)

**Comment by AirGeoff** [comment]
Just got back to the office. Trying this out now as well as the new v1.0.3 that you just released.

**Comment by marchinram** [comment]
Ok thanks, v1.0.3 should address the issue without you needing to modify the generated Xcode project

**Comment by AirGeoff** [comment]
I removed the old Pilgrim SDK folder and imported the v1.0.3 and am getting an error:

**Comment by marchinram** [comment]
Which version of Unity are you using?

**Comment by marchinram** [comment]
From the docs it looks like the earliest version of Unity with the `AddShellScriptBuildPhase` method is 2018.3

**Comment by AirGeoff** [comment]
Ah, ok, we are still using 2018.2.6f1. I will talk to the team about upgrading, but we are in the middle of a development sprint so we probably won't upgrade for a couple weeks. As soon as we do I will test again and let you know if it is working at that time.

Thank you very much for your help!

**Comment by marchinram** [comment]
I didn't realize this method is only 2018.3+, we're supporting down to 2017.1.5f1+, so I can look into a solution for users pre 2018.3, i'll keep you posted

**Comment by marchinram** [comment]
@AirGeoff version 1.0.4 should add the run script build phase for unity versions under 2018.3 
https://github.com/foursquare/pilgrim-unity-sdk/releases/tag/v1.0.4

**Comment by AirGeoff** [comment]
Thank you! Testing right now and will let you know shortly.

**Comment by AirGeoff** [comment]
Ok I deleted the old Pilgrim folder, imported the new pilgrim folder, and made a new Xcode build. Went through the same steps in Xcode and I am receiving a new error when trying to distribute the app:

Failed to verify bitcode in Pilgrim.framework/Pilgrim:
error: Cannot extract bundle from /var/folders/r8/2_5xnmrd2_z1v0vz21947qbr0000gp/T/IDEDistributionOptionThinning.~~~S56BRV/Payload/AirEverywherePOC.app/Frameworks/Pilgrim.framework/Pilgrim (i386)

**Comment by marchinram** [comment]
This looks like the same error, it's trying to use bitcode on i386 as before, it's not stripping out that architecture from the binary.  Can you double check the `Build Phases` tab in Xcode and ensure it has a phase named `Pilgrim Strip Frameworks`, v1.0.4 should be adding that

<img width="766" alt="screenshot" src="https://user-images.githubusercontent.com/197929/53139583-b1039000-354f-11e9-8717-a383280666bc.png">

**Comment by AirGeoff** [comment]
I just checked and I do not have that, just the copy pilgrim framework build phase:

<img width="868" alt="screen shot 2019-02-20 at 6 48 17 pm" src="https://user-images.githubusercontent.com/47788677/53140264-02f0e980-3541-11e9-821c-111f750b4b4b.png">

**Comment by marchinram** [comment]
Can you try manually adding a new run script build phase by clicking the `+` above all the phases then `New Run Script Phase`.  It should default `/bin/sh` for the shell, and paste the following code in the text field
```
${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Pilgrim.framework/strip-frameworks.sh
```

Then try to build again, I will investigate why this isn't being added to the Xcode project when building for iOS, v1.0.4 should be doing this, btw which version of Xcode are you using?

**Comment by AirGeoff** [comment]
Okay update on this. I deleted the xcode project, reverted my changes through git, did the install of v.1.0.4 in Unity again, built another xcode project, and it is now showing up. I then tried to distribute the app and I am no longer receiving the error, so I must have missed something during the first rebuild, but all is good now. I think you can mark this issue as fixed.

Thank you so much for your help!

**Comment by marchinram** [comment]
Ok great! Glad it works
